- hosts: terraform-ansible
  tasks:
  - name: Instalando Python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes #Atualizar os pacotes
    become: yes
  - name: Instalando dependencias com o pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando Projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
  - name: Alterando Host do Settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes #Caso não encontre o arquivo ou o referencial, não faça nada


    